name: main Branch CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run tests
        run: mvn -B test

      - name: Build with Maven
        run: mvn -B package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: TicTacToe-Artifact
          path: target/TicTacToe-1.0-RELEASE.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Zulu 17 JVM for deployment
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download .jar artifact
        uses: actions/download-artifact@v2
        with:
          name: TicTacToe-Artifact
          path: target/

      - name: Deploy to GitHub Releases
        id: deploy
        uses: softprops/action-gh-release@v1
        with:
          tag_name: TicTacToe_v1.0
          files: target/TicTacToe-1.0-RELEASE.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
